import Head from "next/head";
import QuoteBox from "./components/QuoteBox";

export default function Home() {
  return (
    <>
      <Head>
        <title>Random Quotes Generator</title>
        <meta name="description" content="Random Quotes Generator. FreeCodeCamp Front-End Development Libraries Certification. Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.3.0/uicons-bold-rounded/css/uicons-bold-rounded.css'/>
        <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.3.0/uicons-brands/css/uicons-brands.css'/>
        <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.3.0/uicons-solid-straight/css/uicons-solid-straight.css'/>

      </Head>
      <main>
        <QuoteBox/>      
        <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
      </main>
    </>
  );
}
